// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartWasteManagement.Data;

#nullable disable

namespace PoriskarBD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226181812_RemoveAdminSeed")]
    partial class RemoveAdminSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartWasteManagement.Models.CollectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CollectorId")
                        .HasColumnType("int");

                    b.Property<int>("WasteReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectorId");

                    b.HasIndex("WasteReportId")
                        .IsUnique();

                    b.ToTable("CollectionLogs");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.CollectionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("CollectionSchedules");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@waste.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$9G7T5vKnByGaHOGHnSs4IOXSRi7e2PBjFlQVnMU5Ts5dr7RrxMMKu",
                            Role = 2
                        });
                });

            modelBuilder.Entity("SmartWasteManagement.Models.WasteReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("CollectorId");

                    b.ToTable("WasteReports");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.CollectionLog", b =>
                {
                    b.HasOne("SmartWasteManagement.Models.User", "Collector")
                        .WithMany("CollectionLogs")
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWasteManagement.Models.WasteReport", "WasteReport")
                        .WithOne("CollectionLog")
                        .HasForeignKey("SmartWasteManagement.Models.CollectionLog", "WasteReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collector");

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.CollectionSchedule", b =>
                {
                    b.HasOne("SmartWasteManagement.Models.Zone", "Zone")
                        .WithMany("Schedules")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.User", b =>
                {
                    b.HasOne("SmartWasteManagement.Models.Zone", "Zone")
                        .WithMany("Users")
                        .HasForeignKey("ZoneId");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.WasteReport", b =>
                {
                    b.HasOne("SmartWasteManagement.Models.User", "Citizen")
                        .WithMany("ReportedIssues")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWasteManagement.Models.User", "Collector")
                        .WithMany("AssignedReports")
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Citizen");

                    b.Navigation("Collector");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.User", b =>
                {
                    b.Navigation("AssignedReports");

                    b.Navigation("CollectionLogs");

                    b.Navigation("ReportedIssues");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.WasteReport", b =>
                {
                    b.Navigation("CollectionLog");
                });

            modelBuilder.Entity("SmartWasteManagement.Models.Zone", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
